### ISSUE TITLE
Uniform and Vest Disappearing

### ISSUE THREAD

**Issue by Ed-209a** [jetelain/AceArsenalExtended#4] opened 2021-08-25 14:31 UTC
I have an issue that sounds similar to the ones Mihal190 reported, but I don't know if it is exactly the same issue. 

My Arma3 community just started using this mod with USP AIO, and any time we select a USP uniform or vest slot it completely clears any previous selection, including any contents.

When loading a saved loadout, either uniform or vest (often both) will fail to load.

**Comment by jetelain** [comment] 2021-09-18 09:17
Hi, I was not able to reproduce the issue. Can you explain me step by step how to reproduce ?

**Comment by jetelain** [comment] 2021-09-18 13:22
Might be fixed by #7

**Comment by Ed-209a** [comment] 2021-09-18 16:56
I will do more testing with different combinations of mods.

I will update my post with the results.

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by jetelain** [comment] 2023-03-09 12:34
Hi, the issue seems fixed. It has not been reproduced since.

**Closed by jetelain** 2023-03-09 12:34 UTC
Labels: bug
